// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpglrwgwxuwbskvrpqhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwZ2xyd2d3eHV3YnNrdnJwcWhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NDA5MTIsImV4cCI6MjA2MTMxNjkxMn0.QqzJFcmMMpcm7lbl017lM4ggP4llZOqypDcQqqIcN3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);